[package]
name = "dicedemon"
version = "0.1.0"
authors = ["rigelrozanski <rigel.rozanski@gmail.com>"]

[dependencies]
bip39 = "^0.5.0"
ring = "^0.12.0"
bit-vec = "^0.4.3"
bitreader = "^0.3.0"
structopt = "0.2"
